### ISSUE TITLE
V4 Service endpoint appears to be down

### ISSUE THREAD

**Issue by phatcher** [OData/odataorg.github.io#222]
I'm a developer on Simple.OData.Client and we use http://services.odata.org as a integration test endpoint.

The V3 service is running, but the V4 service returns an internal service error, i.e. https://services.odata.org/V4/OData/OData.svc/$metadata gives and error page with the following stack trace...

ODataWebExperimental.OData.ODataService.CreateDefaultData(DSPMetadata metadata) at ODataWebExperimental.OData.ODataService.CreateDataSource() at Microsoft.OData.Service.DataService`1.CreateDataSourceInstance() at Microsoft.OData.Service.DataService`1.CreateMetadataAndQueryProviders(IDataServiceMetadataProvider& metadataProviderInstance, IDataServiceQueryProvider& queryProviderInstance, Object& dataSourceInstance, Boolean& isInternallyCreatedProvider) at Microsoft.OData.Service.DataService`1.CreateProvider() at Microsoft.OData.Service.DataService`1.HandleRequest() at Microsoft.OData.Service.DataService`1.ProcessRequestForMessage(Stream messageBody) at SyncInvokeProcessRequestForMessage(Object , Object[] , Object[] ) at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs) at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc) at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc) at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage41(MessageRpc& rpc) at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage4(MessageRpc& rpc) at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage31(MessageRpc& rpc) at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage3(MessageRpc& rpc) at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage2(MessageRpc& rpc) at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc) at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage1(MessageRpc& rpc) at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)](url)

**Comment by marabooy** [comment]
@phatcher this seems to be back up. Kindly confirm if it work as expected.
