### ISSUE TITLE
Broken ODATA services

### ISSUE THREAD

**Issue by tndata** [OData/odataorg.github.io#242]
I have always used Excel to demonstrate ODATA , but now none of the services that you expose on
https://services.odata.org/ can be imported in Microsoft Excel.

I also tried the Postman example here https://www.odata.org/odata-services/ but that one fails
As well, I guess your upgrade from HTTP to HTTPS broke most of the endpoints here.

**Comment by marabooy** [comment]
@tndata the services now work with excel, closing the issue. Do let me know if this needs to be re-opened. 

Steps
1. Open excel and navigate to the data tab.
2. Choose get data from other sources > OData feed.
3. Enter the base url  https://services.odata.org/TripPinRESTierService
4. Choose the dataset you want to load and where to load.
